
name: Postgres DB Daily Reports
schedules:
- cron: "0 2 * * *"
  displayName: Daily reports
  branches:
    include:
    - master
  always: true

trigger: none
pr: none
variables:
  serviceConnection: 'Prod-DB-Reporting'
  FROM_ADDRESS: 'db-reporting@mail-db-reporting-prod.platform.hmcts.net'
  FAILURE_ADDRESS: 'dcd-devops-support@hmcts.net' # to be verified

jobs:
  - job: rd_judicial_data
    pool:
      name: 'hmcts-ss-prod'
    steps:
      - task: AzureCLI@2
        displayName: 'Get access token'
        name: gettoken
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: 'inlineScript'
          inlineScript: |
            #!/bin/bash
            set -ex
            output=`az account get-access-token --resource-type oss-rdbms --query accessToken -o tsv`
            echo $output
            echo "##vso[task.setvariable variable=PGPASSWORD]$output"
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: $(serviceConnection)
          KeyVaultName: 'sendgridprod'
          SecretsFilter: 'hmcts-db-reporting-api-key'
          RunAsPreJob: false
      - task: Bash@3
        inputs:
          filePath: './scripts/daily/rd-judicial-ref-api-postgres-db-prod-dbrefdata-daily-org-attributes.sh'
        env:
          SENDGRID_APIKEY: $(hmcts-db-reporting-api-key)
