
name: Postgres DB Daily Reports
schedules:
- cron: "0 17 * * *"
  displayName: Private Law Case Status at 5 PM
  branches:
    include:
      - master
  always: true

trigger: none
pr: none
variables:
  serviceConnection: 'Prod-DB-Reporting'
  FROM_ADDRESS: 'db-reporting@mail-db-reporting-prod.platform.hmcts.net'
  FAILURE_ADDRESS: 'dcd-devops-support@hmcts.net' # to be verified

jobs:
  - job: ccd_privatelawcasestatus_5pm
    pool:
      name: 'hmcts-ss-prod'
    strategy:
      maxParallel: 1
      matrix:
        ccd-data-store-api-postgres-db-v15-prod-ccd_data_store-daily-Privatelawcasestatus:
          QUERY: ./scripts/daily/ccd-data-store-api-postgres-db-v15-prod-ccd_data_store-daily-privatelawcasestatus.sh
          TO_ADDRESS: 'privatefamilylawproject@justice.gov.uk'
          AZURE_HOSTNAME: 'ccd-data-store-api-postgres-db-v15-prod.postgres.database.azure.com'
          AZURE_DB: 'ccd_data_store'
          AZURE_DB_USERNAME: "DTS\ Platform\ Operations\ SC"
          SUBJECT: 'Private Law Case Status Daily Report'
    steps:
      - task: AzureCLI@2
        displayName: 'Get access token'
        name: gettoken
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: 'inlineScript'
          inlineScript: |
            #!/bin/bash
            set -ex
            output=`az account get-access-token --resource-type oss-rdbms --query accessToken -o tsv`
            echo $output
            echo "##vso[task.setvariable variable=PGPASSWORD]$output"
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: $(serviceConnection)
          KeyVaultName: 'sendgridprod'
          SecretsFilter: 'hmcts-db-reporting-api-key'
          RunAsPreJob: false
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: $(serviceConnection)
          KeyVaultName: 'ccd-prod'
          SecretsFilter: 'timdaexedata-storageaccount'
          RunAsPreJob: false
      - task: Bash@3
        inputs:
          filePath: 'email_report.sh'
        env:
          SENDGRID_APIKEY: $(hmcts-db-reporting-api-key)
          CONTAINER_NAME: 'daily'
