
name: Postgres DB Daily Reports
schedules:
- cron: "0 2 * * *"
  displayName: Daily reports
  branches:
    include:
    - DTSRD-2954
  always: true

trigger: none
pr: none
variables:
  serviceConnection: 'Prod-DB-Reporting'
  FROM_ADDRESS: 'db-reporting@mail-db-reporting-prod.platform.hmcts.net'
  FAILURE_ADDRESS: 'sabina.sharangdhar@hmcts.net' # to be verified

jobs:
  - job: rd_userprofile
    pool:
      name: 'hmcts-ss-prod'
    steps:
      - task: AzureKeyVault@2
        displayName: 'Get Secrets'
        name: getSecrets
        inputs:
          serviceConnection: 'DCD-CNP-DEV'
          azureSubscription: 'DCD-CNP-DEV'
          KeyVaultName: 'rd-aat'
          SecretsFilter: 'OAUTH2_CLIENT_ID,OAUTH2_CLIENT_SECRET,idam-rd-system-user-username,idam-rd-system-user-password,user-profile-api-POSTGRES-USER,user-profile-api-POSTGRES-HOST,user-profile-api-POSTGRES-DATABASE,user-profile-api-POSTGRES-PASS'
      - task: Bash@3
        displayName: 'Generate and send Bearer token'
        name: generateSendBearer
        inputs:
          filePath: './scripts/daily/rd-userprofile-api-postgres-db-prod-dbuserprofile-daily-suspendedusercomparewithidam.sh'
        env:
          AZURE_DB_USERNAME: $(user-profile-api-POSTGRES-USER)
          AZURE_HOSTNAME: $(user-profile-api-POSTGRES-HOST)
          AZURE_DB: $(user-profile-api-POSTGRES-DATABASE)
          AZURE_PASS: $(user-profile-api-POSTGRES-PASS)
          idam-rd-system-user: $(idam-rd-system-user)
          idam-rd-system-user-password: $(idam-rd-system-user-password)
          OAUTH2_CLIENT_ID: $(OAUTH2_CLIENT_ID)
          OAUTH2_CLIENT_SECRET: $(OAUTH2_CLIENT_SECRET)
          PGPASSWORD : $(user-profile-api-POSTGRES-PASS)
      - task: AzureCLI@2
        displayName: 'Get access token'
        name: gettoken
        inputs:
          serviceConnection: 'DCD-CNP-DEV'
          azureSubscription: 'DCD-CNP-DEV'
          scriptType: bash
          scriptLocation: 'inlineScript'
          inlineScript: |
            #!/bin/bash
            set -ex
            output=`az account get-access-token --resource-type oss-rdbms --query accessToken -o tsv`
            echo $output
            echo "##vso[task.setvariable variable=PGPASSWORD]$output"
      - task: AzureKeyVault@2
        inputs:
          serviceConnection: 'DCD-CNP-DEV'
          azureSubscription: 'DCD-CNP-DEV'
          KeyVaultName: 'sendgridprod'
          SecretsFilter: 'hmcts-db-reporting-api-key'
          RunAsPreJob: false
      - task: Bash@3
        inputs:
          filePath: './scripts/daily/rd-userprofile-api-postgres-db-prod-dbuserprofile-daily-suspendedusercomparewithidam.sh'
        env:
          SENDGRID_APIKEY: $(hmcts-db-reporting-api-key)
          ALL_USERS_FLAG: 1
