
name: Postgres DB Daily Reports
schedules:
- cron: "0 17 * * *"
  displayName: Daily reports
  branches:
    include:
    - master
  always: true

trigger: none
pr: none
variables:
  serviceConnection: 'Prod-DB-Reporting'
  FROM_ADDRESS: 'db-reporting@mail-db-reporting-prod.platform.hmcts.net'
  FAILURE_ADDRESS: 'dcd-devops-support@hmcts.net' # to be verified

jobs:
  - job: rd_userprofile
    pool:
      name: 'hmcts-ss-prod'
    steps:
      - task: AzureCLI@2
        displayName: 'Get access token'
        name: gettoken
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: 'inlineScript'
          inlineScript: |
            #!/bin/bash
            set -ex
            output=`az account get-access-token --resource-type oss-rdbms --query accessToken -o tsv`
            echo $output
            echo "##vso[task.setvariable variable=PGPASSWORD]$output"
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: $(serviceConnection)
          KeyVaultName: 'sendgridprod'
          SecretsFilter: 'hmcts-db-reporting-api-key'
          RunAsPreJob: false
      - task: AzureKeyVault@2
        displayName: 'Get Secrets'
        name: getSecrets
        inputs:
          azureSubscription: 'DCD-CNP-PROD'
          KeyVaultName: 'rd-prod'
          SecretsFilter: 'OAUTH2-CLIENT-SECRET,idam-rd-system-user-username,idam-rd-system-user-password,user-profile-api-POSTGRES-PASS'
      - task: Bash@3
        displayName: 'Generate and send DB Report'
        name: generateSendDBReport
        inputs:
          filePath: './scripts/daily/rd-userprofile-api-postgres-db-prod-dbuserprofile-daily-suspendedusercomparewithidam.sh'
        env:
          OAUTH2_CLIENT_SECRET: $(OAUTH2-CLIENT-SECRET)
          USERNAME: $(idam-rd-system-user-username)
          SYSPASS: $(idam-rd-system-user-password)
          PGPASSWORD: $(user-profile-api-POSTGRES-PASS)
          ALL_USERS_FLAG: 1


