name: Postgres DB Weekly Reports
schedules:
- cron: "0 2 * * 1"
  displayName: Weekly reports
  branches:
    include:
    - master
  always: true

trigger: none
pr: none
variables:
  serviceConnection: 'Prod-DB-Reporting'
  FROM_ADDRESS: 'db-reporting@mail-db-reporting-prod.platform.hmcts.net'
  FAILURE_ADDRESS: 'dcd-devops-support@hmcts.net' # to be verified


jobs:
  - job: ccd_moj_dwp
    timeoutInMinutes: 180
    pool:
      name: 'hmcts-ss-prod'
    steps:
      - task: AzureCLI@1
        displayName: 'Get access token'
        name: gettoken
        inputs:
          azureSubscription: $(serviceConnection)
          scriptLocation: 'inlineScript'
          inlineScript: |
            #!/bin/bash
            set -ex
            output=`az account get-access-token --resource-type oss-rdbms --query accessToken -o tsv`
            echo $output
            echo "##vso[task.setvariable variable=PGPASSWORD]$output"
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: $(serviceConnection)
          KeyVaultName: 'sendgridprod'
          SecretsFilter: 'hmcts-db-reporting-api-key'
          RunAsPreJob: false
      - task: Bash@3
        inputs:
          filePath: './scripts/weekly/ccd-data-store-api-postgres-db-v11-prod-ccd_data_store-daily-ProbateextractfromMoJtoDwP.sh'
        env:
          SENDGRID_APIKEY: $(hmcts-db-reporting-api-key)
  - job:
    timeoutInMinutes: 180
    pool:
      name: 'hmcts-ss-prod'
    strategy:
      maxParallel: 1
      matrix:
        ccd-data-store-api-postgres-db-v11-prod-ccd_data_store-weekly-ccdmetadatareporting:
          QUERY: ./scripts/weekly/ccd-data-store-api-postgres-db-prod-ccd_data_store-weekly-ccdmetadatareporting.sh
          TO_ADDRESS: 'RORDataIngress.Test@HMCTS.NET'
          CC_ADDRESS: '' #to be replaced
          AZURE_DB_USERNAME: "DTS\ Platform\ Operations\ SC@ccd-data-store-api-postgres-db-v11-prod"
          AZURE_HOSTNAME: 'ccd-data-store-api-postgres-db-v11-prod.postgres.database.azure.com'
          AZURE_DB: 'ccd_data_store'
          SUBJECT: 'CCD-Metadata Weekly Reporting'
    steps:
      - task: AzureCLI@1
        displayName: 'Get access token'
        name: gettoken
        inputs:
          azureSubscription: $(serviceConnection)
          scriptLocation: 'inlineScript'
          inlineScript: |
            #!/bin/bash
            set -ex
            output=`az account get-access-token --resource-type oss-rdbms --query accessToken -o tsv`
            echo $output
            echo "##vso[task.setvariable variable=PGPASSWORD]$output"
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: $(serviceConnection)
          KeyVaultName: 'sendgridprod'
          SecretsFilter: 'hmcts-db-reporting-api-key'
          RunAsPreJob: false
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: $(serviceConnection)
          KeyVaultName: 'ccd-prod'
          SecretsFilter: 'timdaexedata-storageaccount'
          RunAsPreJob: false
      - task: Bash@3
        inputs:
          filePath: 'email_report.sh'
        env:
          SENDGRID_APIKEY: $(hmcts-db-reporting-api-key)
          CONTAINER_NAME: 'weeklies'
